### ISSUE TITLE
cannot load such file -- commander/import (LoadError)

### ISSUE THREAD

**Issue by afrigeri** [JesseHerrick/jekyll-ftp#1]
Got this, at the jekyll-ftp deploy command:

/var/lib/gems/2.3.0/gems/jekyll-ftp-0.2.0/bin/jekyll-ftp:7:in `require': cannot load such file -- commander/import (LoadError)
	from /var/lib/gems/2.3.0/gems/jekyll-ftp-0.2.0/bin/jekyll-ftp:7:in `<top (required)>'
	from /usr/local/bin/jekyll-ftp:22:in `load'
	from /usr/local/bin/jekyll-ftp:22:in `<main>'

**Comment by simonneutert** [comment]
if you like, you can try this in the meantime:
https://github.com/simonneutert/ruby-sftp-sync

**Comment by JesseHerrick** [comment]
Hi @afrigeri,

This looks like a dependency issue to me. Have you tried running the command with `bundle exec`?

**Comment by JesseHerrick** [comment]
Hi @afrigeri, I'm closing this. If you're still having issues let me know.
